### PR TITLE
space in JSON example removed

### PR DESCRIPTION
**Pull request by will-s-205**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

Hi everyone. This is my first Pull Request on a repository that is owned by the FCC team. I'm very happy to be here and I want to thank everyone for making people's dreams come through. 

As for my PR, I guess it's just a typo but it took a good chunk of my time to understand that JSON in example doesn't require to have a space between pairs. And because I'm a "genius" I've of course tried to reproduce this space in my JSON output. By any chance, can we make it without space? Thank you so much!

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
I don't think I agree with this change. JSON itself doesn't care about spaces. The space is there to make it more human-readable.

**Comment by will-s-205** [comment]
https://github.com/freeCodeCamp/boilerplate-project-timestamp/pull/89#issuecomment-1555945961
> I don't think I agree with this change. JSON itself doesn't care about spaces. The space is there to make it more human-readable.

Good point. JSON doesn't care about spaces indeed. Unless it's a space inside the quotes (let's agree on that at least) However, the idea to make JSON in a human-readable way could cause confusion and delays in a pleasant user experience delivery. So I took initiative and created this PR to improve the situation.

**Comment by naomi-lgbt** [comment]
> However, the idea to make JSON in a human-readable way could cause confusion and delays in a pleasant user experience delivery.

I'm not sure I understand this comment?

**Comment by will-s-205** [comment]
Closing out this Pull Request due to its insignificance.

ref: https://forum.freecodecamp.org/t/have-pr-for-fcc-but-no-reviewers/611219

**Comment by will-s-205** [comment]
Closing out this Pull Request due to its insignificance.

ref: https://forum.freecodecamp.org/t/have-pr-for-fcc-but-no-reviewers/611219

**Pull request closed without merging**
