### PR TITLE
Updated the express version in the package.json file

### PR DESCRIPTION
**Pull request by AminNeji**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Comment by gikf** [comment]
Hey @AminNeji

Looks like this PR was supposed to be made on your own fork, instead of the original boilerplate repository.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Comment by AminNeji** [comment]
Can i know why ? or because i did not create another branch instead of
pushing the code to the main branch

Le jeu. 10 oct. 2024 à 18:27, Krzysztof G. ***@***.***> a
écrit :

**Comment by gikf** [comment]
Hey @AminNeji,

It looks like you were trying to make PR on your own fork, while this is the original boilerplate repository. Is that not a case?

**Comment by AminNeji** [comment]
okay i did another PR on another branch and you guys closed it even if i
have corrected the code ...

Le jeu. 10 oct. 2024 à 20:14, Krzysztof G. ***@***.***> a
écrit :

**Pull request closed without merging**
