### PR TITLE
fix: rename server.js to index.js for replit debugging

### PR DESCRIPTION
**Pull request by kealanparr**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

If campers clone the freeCodeCamp "Back End Development and APIs Projects" to Replit and try to debug their code - it will not work.

Replit debugging requires the "base" JS file to be named "index.js"

image

A pretty simple PR and if this approach is agreeable, I also would like to change:

- https://github.com/freeCodeCamp/boilerplate-project-headerparser/
- https://github.com/freeCodeCamp/boilerplate-project-urlshortener/
- https://github.com/freeCodeCamp/boilerplate-project-exercisetracker/
- https://github.com/freeCodeCamp/boilerplate-project-filemetadata/

To fix all 5 repo's at once - and to ensure standardisation :)

### CODE REVIEW

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 

Thank you, for taking the time to contribute. I am fine with this change on the other boilerplates, provided it does not break the tests (some tests might query the text in the `server.js` file)

**Comment by kealanparr** [comment]
Fantastic thanks for the response :) 

I'll start making the changes across the other repo's also

**Comment by kealanparr** [comment]
Just an FYI, I've also submitted PR's for:

- [Exercise Tracker service](https://github.com/freeCodeCamp/boilerplate-project-exercisetracker/pull/60)
- [URL Shortener service](https://github.com/freeCodeCamp/boilerplate-project-urlshortener/pull/44)
- [File Metadata service](https://github.com/freeCodeCamp/boilerplate-project-filemetadata/pull/19)
- [Header Parser](https://github.com/freeCodeCamp/boilerplate-project-headerparser/pull/24)

**Review by moT01 — APPROVED** [review]
LGTM @kealanparr 🎉 Thanks for contributing to freeCodeCamp 🎉

**Pull request merged**
